# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/marko/OneDrive/Desktop/ECE532/hdmi_ip/hdmi_ip.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0.xci
# IP: The module: 'hdmi_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marko/OneDrive/Desktop/ECE532/hdmi_ip/hdmi_ip.gen/sources_1/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_auto_us_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marko/OneDrive/Desktop/ECE532/hdmi_ip/hdmi_ip.gen/sources_1/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/marko/OneDrive/Desktop/ECE532/hdmi_ip/hdmi_ip.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0.xci
# IP: The module: 'hdmi_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marko/OneDrive/Desktop/ECE532/hdmi_ip/hdmi_ip.gen/sources_1/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marko/OneDrive/Desktop/ECE532/hdmi_ip/hdmi_ip.gen/sources_1/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
