# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/parser_bd/parser_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser_bd || ORIG_REF_NAME==parser_bd} -quiet] -quiet

# IP: bd/parser_bd/ip/parser_bd_clk_wiz_0_0/parser_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser_bd_clk_wiz_0_0 || ORIG_REF_NAME==parser_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/parser_bd/ip/parser_bd_ila_0_0/parser_bd_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser_bd_ila_0_0 || ORIG_REF_NAME==parser_bd_ila_0_0} -quiet] -quiet

# IP: bd/parser_bd/ip/parser_bd_hcsr04_sensor_0_3/parser_bd_hcsr04_sensor_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser_bd_hcsr04_sensor_0_3 || ORIG_REF_NAME==parser_bd_hcsr04_sensor_0_3} -quiet] -quiet

# XDC: bd/parser_bd/parser_bd_ooc.xdc
