# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/parser/parser.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser || ORIG_REF_NAME==parser} -quiet] -quiet

# IP: bd/parser/ip/parser_clk_wiz_0_0/parser_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser_clk_wiz_0_0 || ORIG_REF_NAME==parser_clk_wiz_0_0} -quiet] -quiet

# IP: bd/parser/ip/parser_ila_0_0/parser_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser_ila_0_0 || ORIG_REF_NAME==parser_ila_0_0} -quiet] -quiet

# IP: bd/parser/ip/parser_xlslice_3_0/parser_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser_xlslice_3_0 || ORIG_REF_NAME==parser_xlslice_3_0} -quiet] -quiet

# IP: bd/parser/ip/parser_xlslice_4_0/parser_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser_xlslice_4_0 || ORIG_REF_NAME==parser_xlslice_4_0} -quiet] -quiet

# IP: bd/parser/ip/parser_xlslice_5_0/parser_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser_xlslice_5_0 || ORIG_REF_NAME==parser_xlslice_5_0} -quiet] -quiet

# IP: bd/parser/ip/parser_xlslice_6_0/parser_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser_xlslice_6_0 || ORIG_REF_NAME==parser_xlslice_6_0} -quiet] -quiet

# IP: bd/parser/ip/parser_xlslice_7_0/parser_xlslice_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser_xlslice_7_0 || ORIG_REF_NAME==parser_xlslice_7_0} -quiet] -quiet

# IP: bd/parser/ip/parser_array_parser_1_0/parser_array_parser_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==parser_array_parser_1_0 || ORIG_REF_NAME==parser_array_parser_1_0} -quiet] -quiet

# XDC: bd/parser/parser_ooc.xdc
