///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package parser_axi_vip_0_1_pkg;
import axi_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter parser_axi_vip_0_1_VIP_PROTOCOL           = 0;
      parameter parser_axi_vip_0_1_VIP_READ_WRITE_MODE    = "READ_ONLY";
      parameter parser_axi_vip_0_1_VIP_INTERFACE_MODE     = 0;
      parameter parser_axi_vip_0_1_VIP_ADDR_WIDTH         = 32;
      parameter parser_axi_vip_0_1_VIP_DATA_WIDTH         = 32;
      parameter parser_axi_vip_0_1_VIP_ID_WIDTH           = 0;
      parameter parser_axi_vip_0_1_VIP_AWUSER_WIDTH       = 0;
      parameter parser_axi_vip_0_1_VIP_ARUSER_WIDTH       = 0;
      parameter parser_axi_vip_0_1_VIP_RUSER_WIDTH        = 0;
      parameter parser_axi_vip_0_1_VIP_WUSER_WIDTH        = 0;
      parameter parser_axi_vip_0_1_VIP_BUSER_WIDTH        = 0;
      parameter parser_axi_vip_0_1_VIP_SUPPORTS_NARROW    = 0;
      parameter parser_axi_vip_0_1_VIP_HAS_BURST          = 1;
      parameter parser_axi_vip_0_1_VIP_HAS_LOCK           = 0;
      parameter parser_axi_vip_0_1_VIP_HAS_CACHE          = 1;
      parameter parser_axi_vip_0_1_VIP_HAS_REGION         = 1;
      parameter parser_axi_vip_0_1_VIP_HAS_QOS            = 1;
      parameter parser_axi_vip_0_1_VIP_HAS_PROT           = 1;
      parameter parser_axi_vip_0_1_VIP_HAS_WSTRB          = 0;
      parameter parser_axi_vip_0_1_VIP_HAS_BRESP          = 0;
      parameter parser_axi_vip_0_1_VIP_HAS_RRESP          = 1;
      parameter parser_axi_vip_0_1_VIP_HAS_ACLKEN         = 0;
      parameter parser_axi_vip_0_1_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////
typedef axi_mst_agent #(parser_axi_vip_0_1_VIP_PROTOCOL, 
                        parser_axi_vip_0_1_VIP_ADDR_WIDTH,
                        parser_axi_vip_0_1_VIP_DATA_WIDTH,
                        parser_axi_vip_0_1_VIP_DATA_WIDTH,
                        parser_axi_vip_0_1_VIP_ID_WIDTH,
                        parser_axi_vip_0_1_VIP_ID_WIDTH,
                        parser_axi_vip_0_1_VIP_AWUSER_WIDTH, 
                        parser_axi_vip_0_1_VIP_WUSER_WIDTH, 
                        parser_axi_vip_0_1_VIP_BUSER_WIDTH, 
                        parser_axi_vip_0_1_VIP_ARUSER_WIDTH,
                        parser_axi_vip_0_1_VIP_RUSER_WIDTH, 
                        parser_axi_vip_0_1_VIP_SUPPORTS_NARROW, 
                        parser_axi_vip_0_1_VIP_HAS_BURST,
                        parser_axi_vip_0_1_VIP_HAS_LOCK,
                        parser_axi_vip_0_1_VIP_HAS_CACHE,
                        parser_axi_vip_0_1_VIP_HAS_REGION,
                        parser_axi_vip_0_1_VIP_HAS_PROT,
                        parser_axi_vip_0_1_VIP_HAS_QOS,
                        parser_axi_vip_0_1_VIP_HAS_WSTRB,
                        parser_axi_vip_0_1_VIP_HAS_BRESP,
                        parser_axi_vip_0_1_VIP_HAS_RRESP,
                        parser_axi_vip_0_1_VIP_HAS_ARESETN) parser_axi_vip_0_1_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      parser_axi_vip_0_1_mst_t  parser_axi_vip_0_1_mst;
//      initial begin : START_parser_axi_vip_0_1_MASTER
//        parser_axi_vip_0_1_mst = new("parser_axi_vip_0_1_mst", `parser_axi_vip_0_1_PATH_TO_INTERFACE);
//        parser_axi_vip_0_1_mst.start_master();
//      end



endpackage : parser_axi_vip_0_1_pkg
