# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.srcs/sources_1/bd/parser/ip/parser_xbar_2/parser_xbar_2.xci
# IP: The module: 'parser_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.srcs/sources_1/bd/parser/ip/parser_xbar_2/parser_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'parser_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.srcs/sources_1/bd/parser/ip/parser_xbar_2/parser_xbar_2.xci
# IP: The module: 'parser_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.srcs/sources_1/bd/parser/ip/parser_xbar_2/parser_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'parser_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
